spring:
  application:
    name: logistics-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      enabled: true
      fail-fast: false

server:
  port: 8111