server:
  port: 8101

spring:
  application:
    name: containers-service
  datasource:
    url: jdbc:mysql://localhost:3306/containers_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
 
logging:
  level:
    com.alicatadosplasencia: DEBUG